name: publish

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 22.19.0
        uses: actions/setup-node@v4
        with:
          node-version: "22.19.0"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm clean-install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Lint code with standard
        run: npm run lint

  publish:
    needs: test
    runs-on: ubuntu-latest
    environment: npm-publish

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 22.19.0
        uses: actions/setup-node@v4
        with:
          node-version: "22.19.0"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm clean-install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Determine npm tag
        id: npm-tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ "$VERSION" == *"-rc"* ]]; then
            echo "tag=--tag rc" >> $GITHUB_OUTPUT
          else
            echo "tag=" >> $GITHUB_OUTPUT
          fi

      - name: Publish to npm
        run: npm publish ${{ steps.npm-tag.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
